version: "3"
services:
  back-end:
    build: ./back-end
    ports:
    - "3002:3002"
    depends_on:
    - mongo
  front-end:
    build: ./front-end
    ports:
    - "3003:8080"
  mongo:
    image: mongo
    ports:
    - "27017:27017"